# Generated by Django 5.1.2 on 2026-02-26 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_alter_cliente_cpf"),
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=1)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pago", models.BooleanField(default=False)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                ("data_pagamento", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiados",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
    ]
